# backend/init_db/Dockerfile
FROM python:3.9-slim
# WORKDIR /app
# COPY requirements.txt. 
# RUN pip install --no-cache-dir -r requirements.txt
COPY setup_couchdb.py .
# Command will be provided by docker-compose